# Generated by Django 4.0.3 on 2022-04-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_address_resque_addrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='resque',
            name='vol',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
