# Generated by Django 4.0.3 on 2022-04-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='vol',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
