# Generated by Django 4.0.3 on 2022-04-21 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0002_volunteer_vol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='vol',
        ),
    ]
